### ISSUE TITLE
legacy-fingerprint

### ISSUE THREAD

**Issue by puyide** [kontalk/tigase-kontalk#1]
Hi Daniele Ricci
       init.properties file have  legacy-fingerprint and  fingerprint,They are GPG generated it? why have two key？Thank you！

**Comment by daniele-athome** [comment]
I'm sorry I should have disabled this repo's issues. Please ask to the kontalk-devel google group.

Anyway legacy-fingerprint is an old parameter for people upgrading from Kontalk 2.x, it's not used anymore.
