### ISSUE TITLE
nohup: redirecting stderr to stdout

### ISSUE THREAD

**Issue by wistis** [kontalk/tigase-kontalk#17]
scripts/tigase.sh start etc/tigase.conf
scripts/tigase.sh: line 83: $'\r': command not found
scripts/tigase.sh: line 141: $'\r': command not found
Starting Tigase: 
nohup: Tigase running pid=7539
root@wistis:/testis# redirecting stderr to stdout

**Comment by daniele-athome** [comment]
Some context maybe :-)

Also we don't provide support to the standalone installation, sorry. We built a Docker environment to ease the whole process: https://github.com/kontalk/xmppserver-docker/
Please refer to that and please discuss issues on the forum.
