### ISSUE TITLE
What are the steps to support FCM instead of GCM ? Soon GCM is deprecating.

### ISSUE THREAD

**Issue by bikramtuladhar** [kontalk/tigase-kontalk#18]
@daniele-athome : I don't know much about xmpp server but it'd be awesome if you guide me so i can test it out and send MR. Thank you in advance

**Comment by daniele-athome** [comment]
Kontalk is already using FCM - although with a deprecated library:

https://github.com/kontalk/tigase-extension/commit/f25d79305302e01e57f10f96fd4a93a4d24e4a64
