### ISSUE TITLE
Attachment upload faild

### ISSUE THREAD

**Issue by webratte** [kontalk/tigase-kontalk#4]
Like Title says.
It's impossible to upload Attachment (Audio and pictures).
This is happens since today I think.
I believe it's a server issue.

I use the current Playstore Version of Kontalk (3.1.1.

**Comment by daniele-athome** [comment]
Sorry temporary issue due to server maintenance. It should work now.

**Comment by webratte** [comment]
Thank you.
Now it works.
Sorry for my impatience.
